apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: curl-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/5g-cloud-labs/new-test-2.git
    targetRevision: charts
    path: charts/curl

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:    
    automated:
      prune: true
      selfHeal: true
