apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-ui-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/5g-cloud-labs/new-test-2.git
    targetRevision: trims
    path: charts/console
    helm:
     parameters:
     - name: Domain
       value: ${ARGOCD_ENV_DOMAIN_NAME}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:    
    automated:
      prune: true
