apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/5g-cloud-labs/new-test-2.git
    targetRevision: trims
    path: charts/multus
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:    
    automated:
      prune: true
      selfHeal: true

