# nginx-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    domain: ${ARGOCD_ENV_DOMAIN_NAME}
    arn: ${ARGOCD_ENV_EFS_ARN}
spec:
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: Always
