apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: istio-system
spec:
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  secretName: tls-cert-secret
  commonName: ${ARGOCD_ENV_DOMAIN_NAME}
  dnsNames:
    - ${ARGOCD_ENV_DOMAIN_NAME}
    - *.${ARGOCD_ENV_DOMAIN_NAME}
