apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sub-prov
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/5g-cloud-labs/new-test-2.git
    targetRevision: trims
    path: 5g/argocd-apps/job-test
    kustomize:
        patches:
        - target:
            kind: Job
            name: sub-prov-job
          patch: |-
            - op: replace
              path: /spec/spec/containers/0/env/mcc
              value: ${ARGOCD_ENV_MCC}
            - op: replace
              path: /spec/rules/0/host
              value: "argocd.${ARGOCD_ENV_DOMAIN_NAME}"
            - op: replace
              path: /spec/rules/1/host
              value: "console.${ARGOCD_ENV_DOMAIN_NAME}"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:    
    automated:
      prune: true
