apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ueransim
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/5g-cloud-labs/new-test-2.git
    targetRevision: trims
    path: 5g/helm-charts/ueransim
    helm:
      releaseName: aws-5gcloudlabs
      values: |
          gnb:
            name: gnb
            configuration1: |-
              mcc: ${ARGOCD_ENV_MCC}
              mnc: ${ARGOCD_ENV_MNC}
          ue:
            name: ue
            command: "./nr-ue -c ../config/ue-config.yaml -n ${ARGOCD_ENV_COUNT}"
            configuration1: |-
              mcc: ${ARGOCD_ENV_MCC}
              mnc: ${ARGOCD_ENV_MNC}
              supi: "imsi-${ARGOCD_ENV_MCC}${ARGOCD_ENV_MNC}0000000001"
       
  destination:
    server: https://kubernetes.default.svc
    namespace: ueransim
  syncPolicy:    
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
