#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# -------------------------------------------------------------------------
# [MODIFIED by 5g-cloud-labs]
# This file is customized for aws-5gcloudlabs.
# -------------------------------------------------------------------------
#

{{- with .Values.gnb }}
{{- if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configmap.name }}
  labels:
    app: {{ $.Values.projectName }}
    component: {{ .name }}
data:
  gnb-config.yaml: |
    # [MODIFIED by 5g-cloud-labs] Separated configuration into two groups:
    # 'configuration1' for user interface manipulation, and 'configuration2' for static/internal settings
    {{- .configuration1 | nindent 4 }}
    {{- .configuration2 | nindent 4 }}
    
    linkIp: 0.0.0.0   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
    # gNB's local IP address for N2 Interface (Usually same with local IP)
{{- if .amf.service.ngap.enabled }}
    ngapIp: 0.0.0.0   
{{- else }}
    ngapIp: {{ $.Values.global.n2networkgNB.n2if.ipAddress }} # [MODIFIED by 5g-cloud-labs] Set N2 (NGAP) interface IP address for gNB
{{- end }}
    gtpIp: {{ $.Values.global.n3networkgNB.n3if.ipAddress }}    # [MODIFIED by 5g-cloud-labs] Set N3 (GTP) interface IP address for gNB
    
    # List of AMF address information
    amfConfigs:
      - address: {{ .amf.n2if.ipAddress }}
        port: {{ .amf.n2if.port }}

{{- end }}
{{- end }}
