#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# -------------------------------------------------------------------------
# [MODIFIED by 5g-cloud-labs]
# This file is customized for aws-5gcloudlabs.
# Networking parameters are inherited from the customized global values.yaml.
# -------------------------------------------------------------------------
#
# [MODIFIED by 5g-cloud-labs]
# Renamed nested parameter group: 'n3network' > 'n3networkgNB'
{{- if .Values.global.n3networkgNB.enabled }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
# [MODIFIED by 5g-cloud-labs]
# Updated value for NAD name.
  name: {{ .Values.global.n3networkgNB.name }}
spec:
# [MODIFIED by 5g-cloud-labs]
# Added host-device CNI plugin configuration.
# Removed macvlan/ipvlan configuration.
# Integrated IPAM with Whereabouts.
  config: '{
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "{{ .Values.global.n3networkgNB.type }}",
      "device": "{{ .Values.global.n3networkgNB.masterIf }}",
      "ipam": {
        "type": "whereabouts",
        "range": "{{ .Values.global.n3networkgNB.subnetIP }}/{{ .Values.global.n3networkgNB.cidr }}",
        "range_start": "{{ .Values.global.n3networkgNB.n3if.ipAddress }}",
        "range_end": "{{ .Values.global.n3networkgNB.n3if.ipAddress }}",
        "routes": [
          {
            "dst": "{{ .Values.global.n3networkgNB.routeDST }}",
            "gw": "{{ .Values.global.n3networkgNB.gatewayIP }}"
          }
        ]
      }
    },
    {
      "type": "tuning",
      "mtu": 9001
    }
  ]
}'
{{- end }}
