apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: istio-vs-console
  namespace: default
spec:
  hosts:
  - HOSTNAME
  gateways:
  - istio-system/istio-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: console-service
        port:
          number: 80
