#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# -------------------------------------------------------------------------
# [MODIFIED by 5g-cloud-labs]
# This file is customized for aws-5gcloudlabs.
# Networking parameters are inherited from the customized global values.yaml.
# -------------------------------------------------------------------------
#

# [MODIFIED by 5g-cloud-labs]
# Renamed nested parameter group: 'n2network' > 'n2networkAMF'        
{{- if and $.Values.isNgapNeeded $.Values.global.n2networkAMF.enabled}}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
# [MODIFIED by 5g-cloud-labs]
# Updated value for NAD name.
  name: {{ .Values.global.n2networkAMF.name }}
spec:
# [MODIFIED by 5g-cloud-labs]
# Replaced MACVLAN with IPVLAN configuration.
# Added IPAM configuration using Whereabouts.
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "{{ .Values.global.n2networkAMF.type }}",
          "capabilities": { "ips": true },
          "master": "{{ .Values.global.n2networkAMF.masterIf }}",
          "mode": "l2",
          "mtu": 9001,
          "ipam": {
            "type": "whereabouts",
            "range": "{{ $.Values.global.n2networkAMF.subnetIP }}/{{ $.Values.global.n2networkAMF.cidr }}",
            "range_start": "{{ $.Values.global.n2networkAMF.n2if.ipAddress }}",
            "range_end": "{{ $.Values.global.n2networkAMF.n2if.ipAddress }}",
            "routes": [{"dst": "{{ $.Values.global.n2networkAMF.routeDST }}",
            "gw": "{{ $.Values.global.n2networkAMF.gatewayIP }}"}]
         }
        }
      ]
    }'
{{- end }}
