name: Release Helm Chart

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |
          mkdir -p docs
          helm package charts/console --destination docs

      - name: Generate Helm repo index
        run: |
          helm repo index docs \
            --url https://5g-cloud-labs.github.io/new-test-2

      - name: Commit and push Helm artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs
          git commit -m "Release Helm chart $GITHUB_REF_NAME"
          git push
